[workspace]
resolver = "3"
members = [
    "libs/engine/compute-api",
    "libs/engine/compute-cpu",
    "libs/engine/domain-core",
    "libs/graph/core",
    "libs/isekai/capi-bridge",
    "libs/isekai/wasm-bridge",
    "libs/domains/procgen/generation-wasm",
    "libs/domains/procgen/discretize",
    "libs/domains/procgen/tileset-wfc",
    "libs/domains/procgen/terrain-generation",
    "libs/domains/procgen/structure-generation",
    "libs/domains/procgen/construction-wasm",
    "tools/rust-api-docgen",
]
