// G-006 tests. `appendWorkspaceMember` is tested purely against scratch
// text, never a real file. `scaffoldCrateFiles` is tested by generating
// into a real, in-repo, non-gitignored scratch directory -- a true OS
// temp directory would sit outside the repo entirely, and Nx's default
// project-graph construction only crawls the actual repo tree (excludes
// .gitignore'd paths too) -- confirmed empirically before writing this
// file (see docs/history/PLANNING_LOG.md's G-tooling section) that neither
// an OS tmpdir nor `spikes/` (gitignored) would ever be Nx-discoverable,
// which is exactly G-006's own "valid crate *and graph*" criterion.
// The scratch directory is always deleted afterward and never `git
// add`ed -- master source S4.3 still applies: no permanent speculative
// crate.

import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { randomUUID } from "node:crypto";
import { readFile, rm, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import test from "node:test";
import { appendWorkspaceMember, scaffoldCrateFiles, setProjectRoot } from "./generate-rust-crate.mjs";

const root = resolve(import.meta.dirname, "../..");

test("appendWorkspaceMember inserts alphabetically at start/middle/end and is idempotent", () => {
  const before = '[workspace]\nresolver = "3"\nmembers = [\n    "libs/a",\n    "libs/c",\n]\n';

  const middle = appendWorkspaceMember(before, "libs/b");
  assert.match(middle, /"libs\/a",\s*\n\s*"libs\/b",\s*\n\s*"libs\/c",/);

  const start = appendWorkspaceMember(before, "libs/0-first");
  assert.match(start, /\[\s*\n\s*"libs\/0-first",\s*\n\s*"libs\/a",/);

  const end = appendWorkspaceMember(before, "libs/z-last");
  assert.match(end, /"libs\/c",\s*\n\s*"libs\/z-last",\s*\n\s*\]/);

  const insertedOnce = appendWorkspaceMember(before, "libs/b");
  const insertedTwice = appendWorkspaceMember(insertedOnce, "libs/b");
  assert.equal(insertedTwice, insertedOnce, "re-inserting an existing member must not duplicate it");
});

test("appendWorkspaceMember leaves unrelated Cargo.toml content untouched", () => {
  const before = '[workspace]\nresolver = "3"\nmembers = [\n    "libs/a",\n]\n';
  const after = appendWorkspaceMember(before, "libs/b");
  assert.match(after, /^\[workspace\]/);
  assert.match(after, /resolver = "3"/);
});

test("scaffoldCrateFiles produces a real crate: correct content, cargo check passes, and Nx discovers it", async (t) => {
  const scratchId = randomUUID().slice(0, 8);
  const nxProjectName = `zzz-generator-test-${scratchId}`;
  const packageName = `grafting-generator-test-${scratchId}`;
  const repoRelative = `libs/.generator-test-${scratchId}`;
  const targetDir = resolve(root, repoRelative);

  t.after(async () => {
    await rm(targetDir, { recursive: true, force: true });
  });

  const { files } = await scaffoldCrateFiles({
    targetDir,
    name: nxProjectName,
    packageName,
    tags: ["scope:test", "lang:rust", "platform:cross", "type:lib"],
    description: "Scratch crate generated by a test -- never committed, deleted at the end of this test.",
  });
  await setProjectRoot(targetDir, repoRelative);

  assert.equal(files.length, 5, "Cargo.toml, src/lib.rs, README.md, AGENTS.md, project.json");

  const cargoTomlOriginal = await readFile(resolve(targetDir, "Cargo.toml"), "utf8");
  assert.match(cargoTomlOriginal, new RegExp(`name = "${packageName}"`));
  assert.match(cargoTomlOriginal, /edition = "2024"/);
  assert.match(cargoTomlOriginal, /publish = false/);

  const libRs = await readFile(resolve(targetDir, "src/lib.rs"), "utf8");
  assert.match(libRs, /^\/\/!/, "src/lib.rs should start with a module doc comment, matching every real crate");

  const projectJson = JSON.parse(await readFile(resolve(targetDir, "project.json"), "utf8"));
  assert.equal(projectJson.name, nxProjectName);
  assert.equal(projectJson.root, repoRelative);
  assert.ok(projectJson.targets.check, "check target must exist");
  assert.ok(projectJson.targets.test, "test target must exist");
  assert.equal(projectJson.metadata.graphIr._comment, undefined, "no stale placeholder _comment, matching graph-core's newer convention");

  // cargo check: this scratch crate is nested inside the real repo's
  // Cargo workspace tree but is not a real member. Confirmed empirically
  // before writing this test: Cargo refuses to check it ("current
  // package believes it's in a workspace when it's not") unless it opts
  // out via its own empty [workspace] table -- appended here, strictly
  // after the real-template assertions above, so it can never affect
  // what a real (non-test) invocation of the generator produces.
  await writeFile(resolve(targetDir, "Cargo.toml"), `${cargoTomlOriginal}\n[workspace]\n`);
  execFileSync("cargo", ["check"], { cwd: targetDir, stdio: "pipe" });

  // The actual "and graph" half of G-006's real acceptance criterion
  // ("valid crate and graph") -- proven, not assumed. Confirmed
  // empirically before writing this test that Nx's default project
  // discovery finds a scratch project.json placed here.
  const nxProjectsRaw = execFileSync("nx", ["show", "projects", "--json"], {
    cwd: root,
    encoding: "utf8",
    shell: true,
  });
  const nxProjects = JSON.parse(nxProjectsRaw.trim().split("\n").pop());
  assert.ok(nxProjects.includes(nxProjectName), `expected Nx to discover ${nxProjectName}, got: ${nxProjectsRaw}`);
});
