<#
.SYNOPSIS
    Downloads (once, cached) the flatc version the published
    Google.FlatBuffers NuGet package actually supports, for C# codegen
    only.

.DESCRIPTION
    The primary pinned `flatc` (tools/flatc-version.txt, 25.12.19) is
    used for Rust/TS generation. Verified against nuget.org: the
    Google.FlatBuffers package has not been published past 25.2.10 --
    generated C# calls a version-marker method
    (`FlatBufferConstants.FLATBUFFERS_<version>()`) that only exists in
    the runtime package matching the *generator* that produced it, so
    C# code generated by 25.12.19 fails to compile against the 25.2.10
    runtime (confirmed empirically, not assumed -- see
    contracts/README.md). Using a second, older, equally-pinned `flatc`
    for the C# generation step specifically is the real fix, not a
    workaround: the wire format itself is unchanged across this range,
    only the generator's own version-marker differs. Re-run this repo's
    own check periodically (does NuGet have a version >= 25.12.19 yet?)
    and drop this second pin once it does.
#>

$ErrorActionPreference = "Stop"
$CSharpFlatcVersion = "25.2.10"
$CacheDir = Join-Path $PSScriptRoot "../.flatc-csharp"
$FlatcExe = Join-Path $CacheDir "flatc.exe"

if (Test-Path $FlatcExe) {
    $existingVersion = (& $FlatcExe --version) -replace "flatc version ", ""
    if ($existingVersion.Trim() -eq $CSharpFlatcVersion) {
        Write-Output $FlatcExe
        exit 0
    }
}

New-Item -ItemType Directory -Force -Path $CacheDir | Out-Null
$zipPath = Join-Path $CacheDir "flatc.zip"
$url = "https://github.com/google/flatbuffers/releases/download/v$CSharpFlatcVersion/Windows.flatc.binary.zip"
Invoke-WebRequest -Uri $url -OutFile $zipPath
Expand-Archive -Path $zipPath -DestinationPath $CacheDir -Force
Remove-Item $zipPath

Write-Output $FlatcExe
