import type { ConstructionRegionTopology } from "@/ports";

import type { AtomicEditOp, EditTarget } from "../orchestration/atomic-edit.ts";
import { HEIGHT_AXIS, HORIZONTAL_AXES } from "../orchestration/atomic-edit.ts";
import { cloudNodes } from "../topology/construction-cloud.ts";
import type { CascadeContext, EditRole, RolePolicy, StructureTypeDefinition } from "./structure-type.ts";
import { allowed, denied } from "./structure-type.ts";
import { IGNORE, type CreationInteraction } from "./creation-interaction.ts";

/**
 * The shared role model for every type generated by `extrude_path`: an
 * upright panel whose boundary is a bottom run at the baseline and a top run
 * one `height` above it. Walls and towers are both this shape -- a tower is
 * a closed ring of such panels with arc edges instead of straight ones, not
 * a different topology.
 *
 * **Where the roles come from.** `extrude_path` emits one panel's cycle as
 * `[bottomStart, bottomEnd, topEnd, topStart]`, and `straight_cycle_region`
 * turns that into edges `0: bottom`, `1: end post`, `2: top`, `3: start
 * post`. This side issued that generation call, so it knows the meaning of
 * each slot by construction -- Rust neither tags nor reports a role. Height
 * comparison is used rather than the raw index so a panel that has since
 * been subdivided (a T-junction weld inserting a vertex mid-run) still
 * classifies correctly; both rules describe the very same creation shape.
 */

export const PANEL_ROLES = {
  bottomCorner: "panel-bottom-corner",
  topCorner: "panel-top-corner",
  bottomEdge: "panel-bottom-edge",
  topEdge: "panel-top-edge",
  post: "panel-post",
  body: "panel-body",
  unknown: "panel-unknown",
} as const;

function baselineY(topology: ConstructionRegionTopology): number {
  return Math.min(...topology.nodes.map((node) => node.position.y));
}

function isAtBaseline(topology: ConstructionRegionTopology, nodeId: string): boolean {
  const node = topology.nodes.find((candidate) => candidate.id === nodeId);
  if (node === undefined) return false;
  return Math.abs(node.position.y - baselineY(topology)) < 1e-3;
}

function edgeOf(topology: ConstructionRegionTopology, edgeId: string) {
  for (const loop of [...topology.outerLoops, ...topology.holes]) {
    const edge = loop.find((candidate) => candidate.edgeId === edgeId);
    if (edge !== undefined) return edge;
  }
  return undefined;
}

export function panelRoleFor(topology: ConstructionRegionTopology, target: EditTarget): EditRole {
  if (target.kind === "region") return PANEL_ROLES.body;
  if (target.kind === "vertex") {
    return isAtBaseline(topology, target.nodeId) ? PANEL_ROLES.bottomCorner : PANEL_ROLES.topCorner;
  }
  const edge = edgeOf(topology, target.edgeId);
  if (edge === undefined) return PANEL_ROLES.unknown;
  const startAtBaseline = isAtBaseline(topology, edge.startNodeId);
  const endAtBaseline = isAtBaseline(topology, edge.endNodeId);
  if (startAtBaseline && endAtBaseline) return PANEL_ROLES.bottomEdge;
  if (!startAtBaseline && !endAtBaseline) return PANEL_ROLES.topEdge;
  return PANEL_ROLES.post;
}

/**
 * A panel's bottom corner drags its own paired top corner along by the
 * **same** delta, so the panel stays upright instead of shearing. The pair
 * is the boundary node directly above it (same XZ, greater Y) -- the very
 * relationship `extrude_path` created it with.
 *
 * Searched across the whole cloud, not the grabbed face. Two panels welded
 * at a column reference one pair of nodes, so reading either face alone
 * happens to give the same answer today -- but a column standing taller on
 * one side than the other is the same corner with two pairs, and which of
 * them a drag found would otherwise depend on which panel the pointer
 * landed on. The cloud is the run; the run is what a corner belongs to.
 */
function pairedTopCorners(context: CascadeContext): readonly AtomicEditOp[] {
  const { cloud, target, delta } = context;
  if (target.kind !== "vertex") return [];
  const nodes = cloudNodes(cloud);
  const moved = nodes.find((node) => node.id === target.nodeId);
  if (moved === undefined) return [];
  return nodes
    .filter(
      (node) =>
        node.id !== moved.id &&
        Math.abs(node.position.x - moved.position.x) < 1e-3 &&
        Math.abs(node.position.z - moved.position.z) < 1e-3 &&
        node.position.y > moved.position.y,
    )
    .map((node) => ({
      kind: "move-vertex" as const,
      nodeId: node.id,
      position: {
        x: node.position.x + delta.x,
        y: node.position.y + delta.y,
        z: node.position.z + delta.z,
      },
    }));
}

export function panelPolicyFor(role: EditRole): RolePolicy {
  switch (role) {
    case PANEL_ROLES.bottomCorner:
      // One corner of one panel. Whatever else references the node moves
      // with it because the graph says so, not because the gesture reached
      // for it.
      return allowed(role, HORIZONTAL_AXES, "surface", pairedTopCorners);
    case PANEL_ROLES.topCorner:
      return allowed(role, HEIGHT_AXIS, "surface");
    case PANEL_ROLES.bottomEdge:
      // A whole bottom run drags horizontally; its own two corners each
      // carry their paired top corner through the same cascade the corner
      // role uses, so this needs no separate rule.
      return allowed(role, HORIZONTAL_AXES, "surface");
    case PANEL_ROLES.topEdge:
      return allowed(role, HEIGHT_AXIS, "surface");
    case PANEL_ROLES.post:
      // A vertical post moves as one rigid unit -- `moveEdge` already
      // carries both of its endpoints.
      return allowed(role, HORIZONTAL_AXES, "surface");
    case PANEL_ROLES.body:
      // Grabbing the body means the wall, not the panel under the pointer.
      // Moving one panel of a welded run drags the columns it shares with
      // its neighbours and leaves the rest standing, which shears the run
      // -- the shape a wall can never legitimately take. Every member moves
      // by the same delta instead, and a lone panel is a cloud of one, so
      // this is not two behaviours.
      return allowed(role, HORIZONTAL_AXES, "cloud");
    default:
      return denied(role, "this part of the panel has no editing role");
  }
}

/**
 * A panel is built *on top of* whatever is already there and consumes
 * nothing: a wall standing on terrain leaves that terrain intact, and two
 * walls crossing weld at their shared corners rather than eating each other.
 * That is the whole of the panel side of the interaction table.
 */
export function panelInteractionOver(_coveredType: string): CreationInteraction {
  return IGNORE;
}

/** Builds one `extrude_path`-generated structure type on the shared panel model. */
export function panelStructureType(
  surfaceType: string,
  label: string,
  creation: string,
): StructureTypeDefinition {
  return Object.freeze({
    surfaceType,
    label,
    creation,
    roleFor: panelRoleFor,
    policyFor: panelPolicyFor,
    interactionOver: panelInteractionOver,
  });
}
