//! Generic all-or-nothing replacement of application-selected regions.
//!
//! The caller owns both the selection and the generated geometry. This
//! module only makes the otherwise necessary "remove old faces, add new
//! faces" sequence safe: failed target registration must leave the live graph
//! untouched.

use std::collections::HashSet;

use serde::Deserialize;

use grafting_graph_core::{ContourTopology, Edge, EdgeId, Node, NodeId, RegionId, SurfaceRegistry};

use crate::editing::SessionGraph;
use crate::mesh::{region_id_from_wire, region_id_to_wire};
use crate::region_editing::{apply_add_patch, AddPatchRequest, AddPatchResponse};

/// One application-selected, whole-region replacement.
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ApplyPatchReplacementRequest {
    /// Stable identity used by session-level undo/redo bookkeeping.
    pub operation_id: String,
    /// Exact existing regions to supersede; no geometric selection happens here.
    pub source_surface_keys: Vec<Vec<String>>,
    /// Complete replacement geometry generated by the application.
    pub patch: AddPatchRequest,
    #[serde(default)]
    pub graph_patch: Option<GraphPatchRequest>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GraphPatchRequest {
    pub nodes: Vec<GraphPatchNode>,
    #[serde(default)]
    pub removed_edge_ids: Vec<String>,
    pub edges: Vec<GraphPatchEdge>,
}

#[derive(Debug, Deserialize)]
pub struct GraphPatchNode {
    pub id: String,
    pub position: [f32; 3],
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GraphPatchEdge {
    pub edge_id: String,
    pub start_node_id: String,
    pub end_node_id: String,
}

/// Runs the replacement on cloned state and publishes it only when every
/// replacement face registered. `skipped_region_ids` is therefore an error,
/// not a partial success: preserving the standing geometry is safer than
/// leaving a hole where a face was refused.
pub fn apply_patch_replacement(
    graph: &mut SessionGraph,
    surfaces: &mut SurfaceRegistry,
    topology: &mut ContourTopology,
    known_regions: &mut HashSet<RegionId>,
    request: ApplyPatchReplacementRequest,
) -> Result<AddPatchResponse, String> {
    if request.operation_id.is_empty() {
        return Err("patch replacement requires an operation identity".into());
    }

    let selected = request
        .source_surface_keys
        .iter()
        .map(|key| region_id_from_wire(key))
        .collect::<Result<Vec<_>, _>>()?;

    let mut next_graph = graph.clone();
    let mut next_surfaces = surfaces.clone();
    let mut next_topology = topology.clone();
    let mut next_known_regions = known_regions.clone();

    if let Some(graph_patch) = request.graph_patch {
        for edge_id in graph_patch.removed_edge_ids {
            let id = EdgeId::new(edge_id).map_err(|error| error.to_string())?;
            if next_graph.edge(&id).is_some() {
                next_graph
                    .remove_edge(&id)
                    .map_err(|error| error.to_string())?;
            }
        }
        for node in graph_patch.nodes {
            let id = NodeId::new(node.id).map_err(|error| error.to_string())?;
            if next_graph.node(&id).is_none() {
                next_graph
                    .add_node(Node::new(id, node.position))
                    .map_err(|error| error.to_string())?;
            }
        }
        for edge in graph_patch.edges {
            let id = EdgeId::new(edge.edge_id).map_err(|error| error.to_string())?;
            if next_graph.edge(&id).is_some() {
                continue;
            }
            let source = NodeId::new(edge.start_node_id).map_err(|error| error.to_string())?;
            let target = NodeId::new(edge.end_node_id).map_err(|error| error.to_string())?;
            next_graph
                .add_edge(Edge::new(id, source, target, ()))
                .map_err(|error| error.to_string())?;
        }
    }

    let mut candidate_nodes = HashSet::<NodeId>::new();
    for region_id in &selected {
        if next_topology.region(region_id).is_none() {
            return Err(format!(
                "patch replacement source region is no longer present: {}",
                region_id.as_str()
            ));
        }
        let removed = next_topology
            .remove_region(region_id)
            .map_err(|error| error.to_string())?;
        for loop_ in removed.outer_loops().iter().chain(removed.holes().iter()) {
            for use_ in loop_ {
                if let Some(edge) = next_topology.edge(use_.edge()) {
                    candidate_nodes.insert(edge.start_node().clone());
                    candidate_nodes.insert(edge.end_node().clone());
                }
            }
        }
        next_surfaces
            .remove_region_surface(region_id)
            .map_err(|error| error.to_string())?;
        next_known_regions.remove(region_id);
    }

    let mut response = apply_add_patch(
        &mut next_graph,
        &mut next_topology,
        &mut next_surfaces,
        request.patch,
    )?;
    if !response.skipped_region_ids.is_empty() {
        return Err(format!(
            "patch replacement target patch was refused: {}",
            response.skipped_region_ids.join(", ")
        ));
    }
    for key in &response.outcome.created_surface_keys {
        next_known_regions.insert(region_id_from_wire(key)?);
    }

    for region_id in &selected {
        response
            .outcome
            .removed_surface_keys
            .push(region_id_to_wire(region_id));
    }
    next_topology.prune_unused_edges();
    let nodes_in_use = next_topology.nodes_in_use();
    for node_id in candidate_nodes {
        if nodes_in_use.contains(&node_id) {
            continue;
        }
        next_graph
            .remove_node(&node_id)
            .map_err(|error| error.to_string())?;
        response
            .outcome
            .removed_node_ids
            .push(node_id.as_str().to_owned());
    }

    *graph = next_graph;
    *surfaces = next_surfaces;
    *topology = next_topology;
    *known_regions = next_known_regions;
    Ok(response)
}

#[cfg(test)]
mod tests {
    use super::*;
    use grafting_graph_core::{straight_cycle_region, Graph, Node, SurfaceType};

    use crate::region_editing::{OrientedEdgeUseDto, PatchRegionDto};

    fn quad() -> (
        SessionGraph,
        ContourTopology,
        SurfaceRegistry,
        HashSet<RegionId>,
        RegionId,
    ) {
        let graph: SessionGraph = Graph::try_from_parts(
            vec![
                Node::new(NodeId::new("a").unwrap(), [0.0, 0.0, 0.0]),
                Node::new(NodeId::new("b").unwrap(), [1.0, 0.0, 0.0]),
                Node::new(NodeId::new("c").unwrap(), [1.0, 0.0, 1.0]),
                Node::new(NodeId::new("d").unwrap(), [0.0, 0.0, 1.0]),
            ],
            Vec::new(),
        )
        .unwrap();
        let mut topology = ContourTopology::new();
        let region = straight_cycle_region(
            &mut topology,
            &graph,
            RegionId::new("source").unwrap(),
            &[
                NodeId::new("a").unwrap(),
                NodeId::new("b").unwrap(),
                NodeId::new("c").unwrap(),
                NodeId::new("d").unwrap(),
            ],
        )
        .unwrap();
        let mut surfaces = SurfaceRegistry::new();
        surfaces
            .add_region_surface(&topology, region.clone(), SurfaceType::new("path"), true)
            .unwrap();
        let known = HashSet::from([region.clone()]);
        (graph, topology, surfaces, known, region)
    }

    #[test]
    fn a_refused_target_leaves_the_source_published() {
        let (mut graph, mut topology, mut surfaces, mut known, source) = quad();
        let request = ApplyPatchReplacementRequest {
            operation_id: "rejected-replacement".into(),
            source_surface_keys: vec![region_id_to_wire(&source)],
            patch: AddPatchRequest {
                nodes: vec![],
                edges: vec![],
                regions: vec![PatchRegionDto {
                    region_id: "bad-target".into(),
                    boundary: vec![OrientedEdgeUseDto {
                        edge_id: "missing-edge".into(),
                        reversed: false,
                    }],
                    holes: vec![],
                    surface_type: "path".into(),
                    physical: true,
                }],
            },
            graph_patch: None,
        };

        assert!(apply_patch_replacement(
            &mut graph,
            &mut surfaces,
            &mut topology,
            &mut known,
            request
        )
        .is_err());
        assert!(
            topology.region(&source).is_some(),
            "the source region remains live"
        );
        assert!(
            surfaces.region_surface(&source).is_some(),
            "the source surface remains live"
        );
        assert!(known.contains(&source), "the source remains enumerable");
    }

    #[test]
    fn a_graph_patch_persists_a_non_region_spine_edge() {
        let (mut graph, mut topology, mut surfaces, mut known, _) = quad();
        let request = ApplyPatchReplacementRequest {
            operation_id: "persist-spine".into(),
            source_surface_keys: vec![],
            patch: AddPatchRequest {
                nodes: vec![],
                edges: vec![],
                regions: vec![],
            },
            graph_patch: Some(GraphPatchRequest {
                nodes: vec![
                    GraphPatchNode {
                        id: "spine:one:0".into(),
                        position: [0.0, 0.0, 0.0],
                    },
                    GraphPatchNode {
                        id: "spine:one:1".into(),
                        position: [1.0, 0.0, 0.0],
                    },
                ],
                removed_edge_ids: vec![],
                edges: vec![GraphPatchEdge {
                    edge_id: "spine-edge:one:0".into(),
                    start_node_id: "spine:one:0".into(),
                    end_node_id: "spine:one:1".into(),
                }],
            }),
        };

        apply_patch_replacement(
            &mut graph,
            &mut surfaces,
            &mut topology,
            &mut known,
            request,
        )
        .unwrap();

        assert!(graph.node(&NodeId::new("spine:one:0").unwrap()).is_some());
        assert!(graph
            .edge(&EdgeId::new("spine-edge:one:0").unwrap())
            .is_some());
    }
}
