//! Generic atomic overlay executor.
//!
//! The application supplies the exact source regions, the already-generated
//! target patch, and the target patch's outer rim. This module has no product
//! rules and creates no target geometry of its own.

use std::collections::HashSet;

use serde::Deserialize;

use grafting_graph_core::{
    ContourEdge, ContourEdgeId, ContourTopology, NodeId, OrientedEdgeUse, RegionId, SurfaceRegistry,
};
use grafting_procgen_surface_transformations::{plan_region_merge_regions, polygonal_contour};

use crate::editing::SessionGraph;
use crate::mesh::{region_id_from_wire, region_id_to_wire};
use crate::region_editing::{
    AddPatchRequest, AddPatchResponse, OrientedEdgeUseDto, apply_add_patch,
};

/// One application-resolved overlay transaction.
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ApplyRegionOverlayRequest {
    /// Stable identity used only for deterministic remainder geometry IDs.
    pub operation_id: String,
    /// Exact regions the application decided to replace.
    pub source_surface_keys: Vec<Vec<String>>,
    /// XZ contour used by the generic overlap planner.
    pub outline: Vec<[f32; 2]>,
    /// Outer boundary of `patch`, in its own walk direction.
    pub boundary: Vec<OrientedEdgeUseDto>,
    /// Complete target geometry generated by the application.
    pub patch: AddPatchRequest,
}

/// Applies one overlay against cloned state and publishes it only on success.
pub fn apply_region_overlay(
    graph: &mut SessionGraph,
    surfaces: &mut SurfaceRegistry,
    topology: &mut ContourTopology,
    known_regions: &mut HashSet<RegionId>,
    request: ApplyRegionOverlayRequest,
) -> Result<AddPatchResponse, String> {
    let mut next_graph = graph.clone();
    let mut next_surfaces = surfaces.clone();
    let mut next_topology = topology.clone();
    let mut next_known_regions = known_regions.clone();
    let response = apply_inner(
        &mut next_graph,
        &mut next_surfaces,
        &mut next_topology,
        &mut next_known_regions,
        request,
    )?;
    *graph = next_graph;
    *surfaces = next_surfaces;
    *topology = next_topology;
    *known_regions = next_known_regions;
    Ok(response)
}

fn apply_inner(
    graph: &mut SessionGraph,
    surfaces: &mut SurfaceRegistry,
    topology: &mut ContourTopology,
    known_regions: &mut HashSet<RegionId>,
    request: ApplyRegionOverlayRequest,
) -> Result<AddPatchResponse, String> {
    if request.operation_id.is_empty() {
        return Err("region overlay requires an operation identity".into());
    }
    if request.outline.len() < 3 || request.boundary.len() != request.outline.len() {
        return Err("region overlay outline and boundary must describe the same closed rim".into());
    }
    let selected = request
        .source_surface_keys
        .iter()
        .map(|key| region_id_from_wire(key))
        .collect::<Result<HashSet<_>, _>>()?;
    let contour = polygonal_contour(request.outline).map_err(|error| error.to_string())?;
    let plan = plan_region_merge_regions(
        graph,
        surfaces,
        topology,
        contour,
        |region_id, _surface_type| selected.contains(region_id),
    )
    .map_err(|error| error.to_string())?;

    let remainder_spec = plan
        .consumed_region_ids()
        .first()
        .map(|first| {
            let surface = surfaces
                .region_surface(first)
                .ok_or("region overlay selected a region without a surface")?;
            let id = RegionId::new(format!("region-overlay-{}-remainder", request.operation_id))
                .map_err(|error| error.to_string())?;
            Ok::<_, String>((id, surface.surface_type().clone(), surface.physical()))
        })
        .transpose()?;

    let mut remainder_loops = Vec::new();
    for (loop_index, source_boundary) in plan.consumed_boundaries().iter().enumerate() {
        let mut loop_ = Vec::new();
        for (edge_index, (start, geometry)) in source_boundary.iter().enumerate() {
            let end = &source_boundary[(edge_index + 1) % source_boundary.len()].0;
            let id = ContourEdgeId::new(format!(
                "region-overlay-{}-remainder-{loop_index}-{edge_index}",
                request.operation_id
            ))
            .map_err(|error| error.to_string())?;
            topology
                .add_edge(
                    graph,
                    ContourEdge::new(id.clone(), start.clone(), end.clone(), *geometry),
                )
                .map_err(|error| error.to_string())?;
            loop_.push(OrientedEdgeUse::forward(id));
        }
        remainder_loops.push(loop_);
    }

    let hole = request
        .boundary
        .iter()
        .rev()
        .map(|use_| {
            let id = ContourEdgeId::new(use_.edge_id.clone()).map_err(|error| error.to_string())?;
            Ok(if use_.reversed {
                OrientedEdgeUse::forward(id)
            } else {
                OrientedEdgeUse::reversed(id)
            })
        })
        .collect::<Result<Vec<_>, String>>()?;

    let mut response = apply_add_patch(graph, topology, surfaces, request.patch)?;
    if !response.skipped_region_ids.is_empty() {
        return Err(format!(
            "region overlay target patch was refused: {}",
            response.skipped_region_ids.join(", ")
        ));
    }
    for key in &response.outcome.created_surface_keys {
        known_regions.insert(region_id_from_wire(key)?);
    }

    if let Some((remainder_id, remainder_type, physical)) = remainder_spec {
        topology
            .add_region(remainder_id.clone(), remainder_loops, vec![hole])
            .map_err(|error| error.to_string())?;
        surfaces
            .add_region_surface(topology, remainder_id.clone(), remainder_type, physical)
            .map_err(|error| error.to_string())?;
        known_regions.insert(remainder_id.clone());
        response
            .outcome
            .created_surface_keys
            .insert(0, region_id_to_wire(&remainder_id));
    }

    let mut candidate_nodes = HashSet::<NodeId>::new();
    for region_id in plan.consumed_region_ids() {
        let removed = topology
            .remove_region(region_id)
            .map_err(|error| error.to_string())?;
        for loop_ in removed.outer_loops().iter().chain(removed.holes().iter()) {
            for use_ in loop_ {
                if let Some(edge) = topology.edge(use_.edge()) {
                    candidate_nodes.insert(edge.start_node().clone());
                    candidate_nodes.insert(edge.end_node().clone());
                }
            }
        }
        surfaces
            .remove_region_surface(region_id)
            .map_err(|error| error.to_string())?;
        known_regions.remove(region_id);
        response
            .outcome
            .removed_surface_keys
            .push(region_id_to_wire(region_id));
    }

    let nodes_in_use = topology.nodes_in_use();
    for node_id in candidate_nodes {
        if nodes_in_use.contains(&node_id) {
            continue;
        }
        graph
            .remove_node(&node_id)
            .map_err(|error| error.to_string())?;
        response
            .outcome
            .removed_node_ids
            .push(node_id.as_str().to_owned());
    }
    topology.prune_unused_edges();
    Ok(response)
}
