import { ALL_AXES } from "../../orchestration/atomic-edit.ts";
import { IGNORE } from "../creation-interaction.ts";
import { allowed, denied, type EditRole, type StructureTypeDefinition } from "../structure-type.ts";
import { roofRecipeGeneration } from "./roof-editing.ts";
import { PANEL_ROLES, panelPolicyFor, panelStructureType } from "../panel/panel-structure.ts";

/**
 * A roof is regenerated whole from the recipe its faces keep: every handle
 * -- its rise, a side's slope, a seam, a footprint corner, a corner pulled
 * out of a side, a dormer -- edits the recipe (`roof-recipe.ts`, through `roof-editing.ts`). How far
 * its eaves reach and whether its leaves curve are the covering's business.
 */
export const roofStructureType: StructureTypeDefinition = Object.freeze<StructureTypeDefinition>({
  surfaceType: "roof", label: "Telhado", creation: "the weighted straight skeleton of its footprint, welded to what it stands on",
  // Its upright faces -- gables, a dormer's front -- take windows like any wall.
  traits: Object.freeze(["accepts-cuts", "roof-generated"] as const),
  roleFor: (_topology, target) => `roof-${target.kind}`,
  policyFor: (role) => role === "roof-region"
    ? { ...allowed(role, ALL_AXES, "cloud"), transport: true }
    : denied(role, "Mova o telhado pela face."),
  interactionOver: () => IGNORE,
  recipe: roofRecipeGeneration,
  // Stood on a floor or a room, it is made again over it whenever that changes.
  reactions: Object.freeze({ reshape: "follow-base" } as const),
  // Its nodes never drag one another: welded to a floor, a side of it pushed
  // must reshape the floor, not carry the roof -- and the floor with it --
  // whole. The roof is made again over what it stands on instead.
  globalHandles: Object.freeze(["pivot", "rotate", "rise", "slope", "seam", "side", "corner", "insert"] as const),
});

/** Upright closures follow the roof recipe while joining wall-cloud editing. */
export const roofTransitionStructureType: StructureTypeDefinition = Object.freeze({
  ...panelStructureType("roof-transition", "Transição parede/telhado", "upright closures generated by a roof", ["partition", "accepts-cuts", "roof-generated"]),
  cloudFamily: "wall",
  // Their upper boundary follows a sloped roof, so the rectangular-panel
  // post law cannot straighten it. Shared lower nodes still edit the platform.
  settle: undefined,
  validateMotion: undefined,
  recipe: roofRecipeGeneration,
  reactions: roofStructureType.reactions,
  cloudHandlesWithRecipe: true,
  globalHandles: Object.freeze([...(roofStructureType.globalHandles ?? []), "foot", "top", "height", "detach"] as const),
  policyFor: (role: EditRole) => role === PANEL_ROLES.bottomCorner || role === PANEL_ROLES.bottomEdge
    ? { ...panelPolicyFor(role), preserveJoined: true }
    : panelPolicyFor(role),
});
