export { resolveBrushShape } from "./brush-shape-params.ts";
export {
  OPENING_SHAPE_PROP,
  clipToConvex,
  isRectangleShape,
  maxUsefulRadius,
  openingOutline,
  propsForShape,
  sameShape,
  shapeFromProps,
  sideArc,
  simplifyLoop,
  type OutlinePoint,
} from "./opening-outline.ts";
export {
  ARC_TOLERANCE,
  clipPathToStrip,
  mapPath,
  openingPath,
  pointAt,
  reversePath,
  segmentExtremes,
  splitSegment,
  startAtLowest,
  type OutlinePath,
  type OutlineSegment,
} from "./opening-path.ts";
export { DEFAULT_STRUCTURE_EDIT_PARAMS, DEFAULT_TOOL_PARAMS, RECTANGLE_OPENING_SHAPE, TOWER_RADIUS_PRESETS, deriveFaceSize, withOpeningKind } from "./tool-types.ts";
export type {
  BrushShapeKind,
  BrushShapeParams,
  ConstructionToolId,
  NoToolParams,
  OpeningParams,
  OpeningShape,
  OpeningSide,
  PathBrushParams,
  PathKind,
  PreviewDescriptor,
  StructureEditParams,
  TerrainSculptMode,
  TerrainSculptParams,
  ToolParamsByTool,
  ToolParamsFor,
  TowerStampParams,
  WallBrushParams,
  WallParams,
} from "./tool-types.ts";
