import type { ConstructionMotionInfluence, ConstructionNodeSnapshot, ConstructionPosition, ConstructionRegionEdge, ConstructionRegionTopology } from "@/ports";

import type { AtomicEditOp, EditTarget } from "../../orchestration/atomic-edit.ts";
import { addPosition, HEIGHT_AXIS, HORIZONTAL_AXES } from "../../orchestration/atomic-edit.ts";
import { cloudNodes } from "../../topology/construction-cloud.ts";
import { reverseGeometry } from "../../topology/boundary-edges.ts";
import type { CascadeContext, EditRole, ReshapeContext, RolePolicy, StructureTrait, StructureTypeDefinition, StructureView } from "../structure-type.ts";
import { allowed, denied } from "../structure-type.ts";
import { IGNORE, type CreationInteraction } from "../creation-interaction.ts";
import { hasTrait } from "../registry.ts";

/**
 * The shared role model for every type generated by `extrude_path`: an
 * upright panel whose boundary is a bottom run at the baseline and a top run
 * one `height` above it. Walls and towers are both this shape -- a tower is
 * a closed ring of such panels with arc edges instead of straight ones, not
 * a different topology.
 *
 * **Where the roles come from.** `extrude_path` emits one panel's cycle as
 * `[bottomStart, bottomEnd, topEnd, topStart]`, and `straight_cycle_region`
 * turns that into edges `0: bottom`, `1: end post`, `2: top`, `3: start
 * post`. This side issued that generation call, so it knows the meaning of
 * each slot by construction -- Rust neither tags nor reports a role. Height
 * comparison is used rather than the raw index so a panel that has since
 * been subdivided (a T-junction weld inserting a vertex mid-run) still
 * classifies correctly; both rules describe the very same creation shape.
 */

export const PANEL_ROLES = {
  bottomCorner: "panel-bottom-corner",
  topCorner: "panel-top-corner",
  bottomEdge: "panel-bottom-edge",
  topEdge: "panel-top-edge",
  post: "panel-post",
  body: "panel-body",
  /** The height widget's upper zone: raises every other level top run currently at the grabbed one's height, table-wide. */
  topSegmentGroup: "panel-top-segment-group",
  /** The height widget's lower zone: the grabbed top run alone -- the same reach as grabbing {@link topEdge} directly. */
  topSegmentSingle: "panel-top-segment-single",
  unknown: "panel-unknown",
} as const;

function baselineY(topology: ConstructionRegionTopology): number {
  return Math.min(...topology.nodes.map((node) => node.position.y));
}

function isAtBaseline(topology: ConstructionRegionTopology, nodeId: string): boolean {
  const node = topology.nodes.find((candidate) => candidate.id === nodeId);
  if (node === undefined) return false;
  return Math.abs(node.position.y - baselineY(topology)) < 1e-3;
}

function edgeOf(topology: ConstructionRegionTopology, edgeId: string) {
  return topology.outerLoops.flat().find((candidate) => candidate.edgeId === edgeId);
}

export interface PanelTopRun {
  readonly edge: ConstructionRegionEdge;
  readonly start: ConstructionNodeSnapshot;
  readonly end: ConstructionNodeSnapshot;
}

/** Every run of `topology` with neither end at its baseline: the runs that carry a panel's height. */
export function topRunsOf(topology: ConstructionRegionTopology): readonly PanelTopRun[] {
  const base = baselineY(topology);
  const nodes = new Map(topology.nodes.map((node) => [node.id, node]));
  return topology.outerLoops.flat().flatMap((edge) => {
    const start = nodes.get(edge.startNodeId);
    const end = nodes.get(edge.endNodeId);
    if (start === undefined || end === undefined) return [];
    if (Math.abs(start.position.y - base) < 1e-3 || Math.abs(end.position.y - base) < 1e-3) return [];
    return [{ edge, start, end }];
  });
}

export function panelRoleFor(topology: ConstructionRegionTopology, target: EditTarget): EditRole {
  if (target.kind === "region") return PANEL_ROLES.body;
  if (target.kind === "vertex") {
    if (!topology.nodes.some((node) => node.id === target.nodeId)) return PANEL_ROLES.unknown;
    return isAtBaseline(topology, target.nodeId) ? PANEL_ROLES.bottomCorner : PANEL_ROLES.topCorner;
  }
  if (target.kind === "edge-zone") {
    // The widget only ever sits on a top run, so a stray pick against a
    // bottom run or a post is unknown.
    if (!topRunsOf(topology).some((run) => run.edge.edgeId === target.edgeId)) return PANEL_ROLES.unknown;
    return target.zone === "group" ? PANEL_ROLES.topSegmentGroup : PANEL_ROLES.topSegmentSingle;
  }
  const edge = edgeOf(topology, target.edgeId);
  if (edge === undefined) return PANEL_ROLES.unknown;
  const startAtBaseline = isAtBaseline(topology, edge.startNodeId);
  const endAtBaseline = isAtBaseline(topology, edge.endNodeId);
  if (startAtBaseline && endAtBaseline) return PANEL_ROLES.bottomEdge;
  if (!startAtBaseline && !endAtBaseline) return PANEL_ROLES.topEdge;
  return PANEL_ROLES.post;
}

/** Only actual upright boundary edges transmit movement upwards. Subdivided
 * posts work through successive edges in the shared Rust solver. */
export function panelMotionInfluences(topology: ConstructionRegionTopology): readonly ConstructionMotionInfluence[] {
  const nodes = new Map(topology.nodes.map((node) => [node.id, node.position]));
  return topology.outerLoops.flat().flatMap((edge) => {
    const a = nodes.get(edge.startNodeId), b = nodes.get(edge.endNodeId);
    if (!a || !b || Math.abs(a.x - b.x) > 1e-3 || Math.abs(a.z - b.z) > 1e-3 || Math.abs(a.y - b.y) < 1e-4) return [];
    return [{ from: a.y < b.y ? edge.startNodeId : edge.endNodeId, to: a.y < b.y ? edge.endNodeId : edge.startNodeId, axes: [true, true, true] as const }];
  });
}

export function validatePanelMotion(topology: ConstructionRegionTopology, positions: ReadonlyMap<string, ConstructionPosition>): string | undefined {
  const original = new Map(topology.nodes.map((node) => [node.id, node.position]));
  for (const link of panelMotionInfluences(topology)) {
    const lower = positions.get(link.from) ?? original.get(link.from)!;
    const upper = positions.get(link.to) ?? original.get(link.to)!;
    if (upper.y - lower.y <= 1e-4) return "O movimento colapsaria ou inverteria uma parede conectada.";
    const originalLower = original.get(link.from)!;
    const originalUpper = original.get(link.to)!;
    if (Math.abs(originalLower.x - originalUpper.x) < 1e-3 && Math.abs(originalLower.z - originalUpper.z) < 1e-3
      && (Math.abs(lower.x - upper.x) > 1e-3 || Math.abs(lower.z - upper.z) > 1e-3)) {
      return "O movimento inclinaria uma parede vertical. Mova sua base ou ajuste apenas a elevacao.";
    }
  }
  return undefined;
}

function pairedTopCorners(context: CascadeContext): readonly AtomicEditOp[] {
  const ids = context.target.kind === "vertex" ? [context.target.nodeId]
    : context.target.kind === "edge" ? context.cloud.members.flatMap((member) => member.outerLoops.flat().filter((edge) => edge.edgeId === (context.target as { edgeId: string }).edgeId).flatMap((edge) => [edge.startNodeId, edge.endNodeId])) : [];
  const nodes = new Map(cloudNodes(context.cloud).map((node) => [node.id, node.position]));
  const paired = new Set(context.cloud.members.flatMap((member) => panelMotionInfluences(member)).filter((link) => ids.includes(link.from)).map((link) => link.to));
  return [...paired].map((nodeId) => {
    const p = nodes.get(nodeId)!;
    return { kind: "move-vertex", nodeId, position: { x: p.x + context.delta.x, y: p.y + context.delta.y, z: p.z + context.delta.z } };
  });
}

/** An edge's own start and end nodes, whichever way the loop holding it walks it. */
function canonicalEdge(cloud: CascadeContext["cloud"], edgeId: string): { readonly start: string; readonly end: string } | undefined {
  for (const member of cloud.members) {
    for (const use of member.outerLoops.flat()) {
      if (use.edgeId === edgeId) return use.reversed ? { start: use.endNodeId, end: use.startNodeId } : { start: use.startNodeId, end: use.endNodeId };
    }
  }
  return undefined;
}

/**
 * A panel's top and bottom runs are the same curve at two heights: reshaping
 * one reshapes the run across the panel from it, found through the same
 * upright links a corner drag carries its paired corner by.
 */
function pairedRun(context: ReshapeContext): readonly AtomicEditOp[] {
  const grabbed = canonicalEdge(context.cloud, context.edgeId);
  if (grabbed === undefined) return [];
  const links = context.cloud.members.flatMap((member) => panelMotionInfluences(member));
  const across = (nodeId: string) => links.find((link) => link.from === nodeId)?.to ?? links.find((link) => link.to === nodeId)?.from;
  const start = across(grabbed.start);
  const end = across(grabbed.end);
  if (start === undefined || end === undefined) return [];
  for (const member of context.cloud.members) {
    for (const use of member.outerLoops.flat()) {
      if (use.edgeId === context.edgeId) continue;
      const own = use.reversed ? { start: use.endNodeId, end: use.startNodeId } : { start: use.startNodeId, end: use.endNodeId };
      if (own.start === start && own.end === end) return [{ kind: "retype-edge", edgeId: use.edgeId, geometry: context.geometry }];
      if (own.start === end && own.end === start) return [{ kind: "retype-edge", edgeId: use.edgeId, geometry: reverseGeometry(context.geometry) }];
    }
  }
  return [];
}

/**
 * The height widget's group zone: every *other* level top run, of any
 * `"partition"`-trait panel anywhere on the table, currently at the same
 * height as the grabbed one -- matched by value at gesture time, never by a
 * standing weld, which is exactly what a structural cascade cannot express
 * and why this is a `groupCascade` rather than a `cascade`.
 *
 * Membership is re-read every tick from `context.allTopologies`, which the
 * orchestrator refreshes each call. Segments that move together by the same
 * delta stay equal throughout the gesture, so this converges to the same
 * group a press-time snapshot would have picked -- it only differs if some
 * other, unrelated edit changes a candidate's height mid-gesture, which
 * would have to race this drag to matter.
 */
function sameHeightGroupCascade(context: CascadeContext): readonly AtomicEditOp[] {
  if (context.target.kind !== "edge-zone") return [];
  const grabbed = canonicalEdge(context.cloud, context.target.edgeId);
  if (grabbed === undefined) return [];
  const cloudPositions = new Map(cloudNodes(context.cloud).map((node) => [node.id, node.position]));
  const grabbedStart = cloudPositions.get(grabbed.start);
  const grabbedEnd = cloudPositions.get(grabbed.end);
  if (grabbedStart === undefined || grabbedEnd === undefined) return [];
  if (Math.abs(grabbedStart.y - grabbedEnd.y) > 1e-3) return []; // The grabbed run itself is not level -- it names no single height to match.
  const height = grabbedStart.y;
  const ops: AtomicEditOp[] = [];
  for (const topology of context.allTopologies ?? []) {
    if (!hasTrait(topology.surfaceType, "partition")) continue;
    for (const { edge, start, end } of topRunsOf(topology)) {
      if (edge.edgeId === context.target.edgeId) continue;
      if (Math.abs(start.position.y - end.position.y) > 1e-3) continue; // Only a level run has one height.
      if (Math.abs(start.position.y - height) > 1e-3) continue;
      ops.push(
        { kind: "move-vertex", nodeId: start.id, position: addPosition(start.position, context.delta) },
        { kind: "move-vertex", nodeId: end.id, position: addPosition(end.position, context.delta) },
      );
    }
  }
  return ops;
}

export function panelPolicyFor(role: EditRole): RolePolicy {
  switch (role) {
    case PANEL_ROLES.bottomCorner:
      // One corner of one panel. Whatever else references the node moves
      // with it because the graph says so, not because the gesture reached
      // for it.
      return allowed(role, HORIZONTAL_AXES, "surface", pairedTopCorners);
    case PANEL_ROLES.topCorner:
      return allowed(role, HEIGHT_AXIS, "surface");
    case PANEL_ROLES.bottomEdge:
      // A whole bottom run drags horizontally; its own two corners each
      // carry their paired top corner through the same cascade the corner
      // role uses, so this needs no separate rule.
      return { ...allowed(role, HORIZONTAL_AXES, "surface", pairedTopCorners), reshape: pairedRun };
    case PANEL_ROLES.topEdge:
      return { ...allowed(role, HEIGHT_AXIS, "surface"), reshape: pairedRun };
    case PANEL_ROLES.topSegmentSingle:
      // The widget's lower zone: the same reach as grabbing the top run
      // itself, nothing more.
      return allowed(role, HEIGHT_AXIS, "surface");
    case PANEL_ROLES.topSegmentGroup:
      // The widget's upper zone: the grabbed run, plus every other level run
      // currently at its height, wherever it stands.
      return { ...allowed(role, HEIGHT_AXIS, "surface"), groupCascade: sameHeightGroupCascade };
    case PANEL_ROLES.post:
      // A vertical post moves as one rigid unit -- `moveEdge` already
      // carries both of its endpoints.
      return allowed(role, HORIZONTAL_AXES, "surface");
    case PANEL_ROLES.body:
      // Grabbing the body means the wall, not the panel under the pointer.
      // Moving one panel of a welded run drags the columns it shares with
      // its neighbours and leaves the rest standing, which shears the run
      // -- the shape a wall can never legitimately take. Every member moves
      // by the same delta instead, and a lone panel is a cloud of one, so
      // this is not two behaviours.
      return allowed(role, HORIZONTAL_AXES, "cloud");
    default:
      return denied(role, "this part of the panel has no editing role");
  }
}

/**
 * A panel is built *on top of* whatever is already there and consumes
 * nothing: a wall standing on terrain leaves that terrain intact, and two
 * walls crossing weld at their shared corners rather than eating each other.
 * That is the whole of the panel side of the interaction table.
 */
export function panelInteractionOver(_covered: StructureView): CreationInteraction {
  return IGNORE;
}

/** Builds one `extrude_path`-generated structure type on the shared panel model. */
export function panelStructureType(
  surfaceType: string,
  label: string,
  creation: string,
  traits: readonly StructureTrait[],
): StructureTypeDefinition {
  return Object.freeze({
    surfaceType,
    label,
    creation,
    traits: Object.freeze([...traits]),
    roleFor: panelRoleFor,
    motionInfluences: panelMotionInfluences,
    validateMotion: validatePanelMotion,
    policyFor: panelPolicyFor,
    interactionOver: panelInteractionOver,
  });
}

/**
 * An opening's own single role: however it is grabbed, there is no atomic
 * expression for "move" or "resize" a rectangle parametrized against its
 * host wall's own travel-and-height rail -- editing one always means
 * recomputing its rim and replacing the whole face, the same "regenerate"
 * escalation terrain uses for its own reason. `composition/tabletop/tools/
 * openings/opening-tool.ts` is the one tool that gesture actually reaches
 * (it both creates and edits), the same way terrain has its own
 * `terrain-sculpt-tool.ts`.
 */
const OPENING_ROLE = "opening-body";

function openingRoleFor(): EditRole {
  return OPENING_ROLE;
}

function openingPolicyFor(role: EditRole): RolePolicy {
  return {
    role,
    resolve: { kind: "regenerate", reason: "uma abertura muda de lugar ou de tamanho recriando seu proprio rim, nao arrastando um vertice isolado." },
    axes: [],
    scope: "surface",
  };
}

/**
 * A door or a window: its own region, every node pinned to a host face in
 * relative coordinates, cutting the host at mesh time rather than through a
 * topological hole. Editing one always replaces it (see
 * {@link openingPolicyFor}).
 */
export const openingStructureType: StructureTypeDefinition = Object.freeze({
  surfaceType: "opening",
  label: "Abertura",
  creation: "one face pinned to its host faces, cutting them where it stands",
  traits: Object.freeze(["cuts"] as const),
  roleFor: openingRoleFor,
  policyFor: openingPolicyFor,
  interactionOver: panelInteractionOver,
});
