import type { ConstructionRegionTopology, ConstructionMotionInfluence, ConstructionPosition } from "@/ports";

import type { AtomicEditOp, EditTarget } from "../../orchestration/atomic-edit.ts";
import { HEIGHT_AXIS, HORIZONTAL_AXES } from "../../orchestration/atomic-edit.ts";
import { cloudNodes } from "../../topology/construction-cloud.ts";
import type { CascadeContext, CutRepair, EditRole, RolePolicy, StructureTypeDefinition } from "../structure-type.ts";
import { allowed, denied } from "../structure-type.ts";
import { IGNORE, type CreationInteraction } from "../creation-interaction.ts";

/**
 * The shared role model for every type generated by `extrude_path`: an
 * upright panel whose boundary is a bottom run at the baseline and a top run
 * one `height` above it. Walls and towers are both this shape -- a tower is
 * a closed ring of such panels with arc edges instead of straight ones, not
 * a different topology.
 *
 * **Where the roles come from.** `extrude_path` emits one panel's cycle as
 * `[bottomStart, bottomEnd, topEnd, topStart]`, and `straight_cycle_region`
 * turns that into edges `0: bottom`, `1: end post`, `2: top`, `3: start
 * post`. This side issued that generation call, so it knows the meaning of
 * each slot by construction -- Rust neither tags nor reports a role. Height
 * comparison is used rather than the raw index so a panel that has since
 * been subdivided (a T-junction weld inserting a vertex mid-run) still
 * classifies correctly; both rules describe the very same creation shape.
 */

export const PANEL_ROLES = {
  bottomCorner: "panel-bottom-corner",
  topCorner: "panel-top-corner",
  bottomEdge: "panel-bottom-edge",
  topEdge: "panel-top-edge",
  post: "panel-post",
  body: "panel-body",
  unknown: "panel-unknown",
} as const;

function baselineY(topology: ConstructionRegionTopology): number {
  return Math.min(...topology.nodes.map((node) => node.position.y));
}

function isAtBaseline(topology: ConstructionRegionTopology, nodeId: string): boolean {
  const node = topology.nodes.find((candidate) => candidate.id === nodeId);
  if (node === undefined) return false;
  return Math.abs(node.position.y - baselineY(topology)) < 1e-3;
}

function edgeOf(topology: ConstructionRegionTopology, edgeId: string) {
  for (const loop of [...topology.outerLoops, ...topology.holes]) {
    const edge = loop.find((candidate) => candidate.edgeId === edgeId);
    if (edge !== undefined) return edge;
  }
  return undefined;
}

export function panelRoleFor(topology: ConstructionRegionTopology, target: EditTarget): EditRole {
  if (target.kind === "region") return PANEL_ROLES.body;
  if (target.kind === "vertex") {
    if (!topology.nodes.some((node) => node.id === target.nodeId)) return PANEL_ROLES.unknown;
    return isAtBaseline(topology, target.nodeId) ? PANEL_ROLES.bottomCorner : PANEL_ROLES.topCorner;
  }
  const edge = edgeOf(topology, target.edgeId);
  if (edge === undefined) return PANEL_ROLES.unknown;
  const startAtBaseline = isAtBaseline(topology, edge.startNodeId);
  const endAtBaseline = isAtBaseline(topology, edge.endNodeId);
  if (startAtBaseline && endAtBaseline) return PANEL_ROLES.bottomEdge;
  if (!startAtBaseline && !endAtBaseline) return PANEL_ROLES.topEdge;
  return PANEL_ROLES.post;
}

/** Only actual upright boundary edges transmit movement upwards. Subdivided
 * posts work through successive edges in the shared Rust solver. */
export function panelMotionInfluences(topology: ConstructionRegionTopology, transport = false): readonly ConstructionMotionInfluence[] {
  const nodes = new Map(topology.nodes.map((node) => [node.id, node.position]));
  const links: ConstructionMotionInfluence[] = [...topology.outerLoops, ...topology.holes].flatMap((loop) => loop.flatMap((edge) => {
    const a = nodes.get(edge.startNodeId), b = nodes.get(edge.endNodeId);
    if (!a || !b || Math.abs(a.x - b.x) > 1e-3 || Math.abs(a.z - b.z) > 1e-3 || Math.abs(a.y - b.y) < 1e-4) return [];
    return [{ from: a.y < b.y ? edge.startNodeId : edge.endNodeId, to: a.y < b.y ? edge.endNodeId : edge.startNodeId, axes: [true, true, true] as const }];
  }));
  // Openings retain their sill offset when their supporting rail is raised.
  // A whole-object translation carries the aperture horizontally as well.
  const base = baselineY(topology);
  const supports = topology.nodes.filter((node) => Math.abs(node.position.y - base) < 1e-4);
  const holeNodes = new Set(topology.holes.flatMap((loop) => loop.map((edge) => edge.startNodeId)));
  for (const support of supports) for (const target of holeNodes) {
    if (target !== support.id) links.push({ from: support.id, to: target, axes: [transport, true, transport] });
  }
  return links;
}

export function validatePanelMotion(topology: ConstructionRegionTopology, positions: ReadonlyMap<string, ConstructionPosition>): string | undefined {
  const original = new Map(topology.nodes.map((node) => [node.id, node.position]));
  for (const link of panelMotionInfluences(topology)) {
    const lower = positions.get(link.from) ?? original.get(link.from)!;
    const upper = positions.get(link.to) ?? original.get(link.to)!;
    if (upper.y - lower.y <= 1e-4) return "O movimento colapsaria ou inverteria uma parede conectada.";
    const originalLower = original.get(link.from)!;
    const originalUpper = original.get(link.to)!;
    if (Math.abs(originalLower.x - originalUpper.x) < 1e-3 && Math.abs(originalLower.z - originalUpper.z) < 1e-3
      && (Math.abs(lower.x - upper.x) > 1e-3 || Math.abs(lower.z - upper.z) > 1e-3)) {
      return "O movimento inclinaria uma parede vertical. Mova sua base ou ajuste apenas a elevacao.";
    }
  }
  const outerIds = topology.outerLoops.flatMap((loop) => loop.map((edge) => edge.startNodeId));
  const outerY = outerIds.map((id) => (positions.get(id) ?? original.get(id)!).y);
  const bottom = Math.min(...outerY), top = Math.max(...outerY);
  for (const edge of topology.holes.flat()) {
    const y = (positions.get(edge.startNodeId) ?? original.get(edge.startNodeId)!).y;
    if (y < bottom - 1e-4 || y > top + 1e-4) return "O movimento colocaria uma abertura fora da parede.";
  }
  return undefined;
}

function pairedTopCorners(context: CascadeContext): readonly AtomicEditOp[] {
  const ids = context.target.kind === "vertex" ? [context.target.nodeId]
    : context.target.kind === "edge" ? context.cloud.members.flatMap((member) => [...member.outerLoops, ...member.holes].flat().filter((edge) => edge.edgeId === (context.target as { edgeId: string }).edgeId).flatMap((edge) => [edge.startNodeId, edge.endNodeId])) : [];
  const nodes = new Map(cloudNodes(context.cloud).map((node) => [node.id, node.position]));
  const paired = new Set(context.cloud.members.flatMap((member) => panelMotionInfluences(member)).filter((link) => ids.includes(link.from)).map((link) => link.to));
  return [...paired].map((nodeId) => {
    const p = nodes.get(nodeId)!;
    return { kind: "move-vertex", nodeId, position: { x: p.x + context.delta.x, y: p.y + context.delta.y, z: p.z + context.delta.z } };
  });
}

export function panelPolicyFor(role: EditRole): RolePolicy {
  switch (role) {
    case PANEL_ROLES.bottomCorner:
      // One corner of one panel. Whatever else references the node moves
      // with it because the graph says so, not because the gesture reached
      // for it.
      return allowed(role, HORIZONTAL_AXES, "surface", pairedTopCorners);
    case PANEL_ROLES.topCorner:
      return allowed(role, HEIGHT_AXIS, "surface");
    case PANEL_ROLES.bottomEdge:
      // A whole bottom run drags horizontally; its own two corners each
      // carry their paired top corner through the same cascade the corner
      // role uses, so this needs no separate rule.
      return allowed(role, HORIZONTAL_AXES, "surface", pairedTopCorners);
    case PANEL_ROLES.topEdge:
      return allowed(role, HEIGHT_AXIS, "surface");
    case PANEL_ROLES.post:
      // A vertical post moves as one rigid unit -- `moveEdge` already
      // carries both of its endpoints.
      return allowed(role, HORIZONTAL_AXES, "surface");
    case PANEL_ROLES.body:
      // Grabbing the body means the wall, not the panel under the pointer.
      // Moving one panel of a welded run drags the columns it shares with
      // its neighbours and leaves the rest standing, which shears the run
      // -- the shape a wall can never legitimately take. Every member moves
      // by the same delta instead, and a lone panel is a cloud of one, so
      // this is not two behaviours.
      return allowed(role, HORIZONTAL_AXES, "cloud");
    default:
      return denied(role, "this part of the panel has no editing role");
  }
}

/**
 * A panel is built *on top of* whatever is already there and consumes
 * nothing: a wall standing on terrain leaves that terrain intact, and two
 * walls crossing weld at their shared corners rather than eating each other.
 * That is the whole of the panel side of the interaction table.
 */
export function panelInteractionOver(_coveredType: string): CreationInteraction {
  return IGNORE;
}

/**
 * A path crossing a wall reads as an opening through it -- `CUT`'s own doc
 * comment already says so -- but framing that opening (jamb consistency,
 * which posts stay structural) is undesigned. Every panel type (wall, door,
 * window, floor, ceiling) shares this gap, since they all share this one
 * builder.
 */
const PANEL_CUT_REPAIR: CutRepair = {
  kind: "unsupported",
  reason: "panels have no repair for a cut yet -- a path cutting through a wall should open it, but framing the opening is undesigned",
};

/** Builds one `extrude_path`-generated structure type on the shared panel model. */
export function panelStructureType(
  surfaceType: string,
  label: string,
  creation: string,
): StructureTypeDefinition {
  return Object.freeze({
    surfaceType,
    label,
    creation,
    roleFor: panelRoleFor,
    motionInfluences: panelMotionInfluences,
    validateMotion: validatePanelMotion,
    policyFor: panelPolicyFor,
    interactionOver: panelInteractionOver,
    repairAfterCut: PANEL_CUT_REPAIR,
  });
}
