// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;


#[allow(unused_imports, dead_code)]
pub mod grafting {

#[allow(unused_imports, dead_code)]
pub mod contracts {


#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_COMMAND_PAYLOAD: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_COMMAND_PAYLOAD: u8 = 4;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_COMMAND_PAYLOAD: [CommandPayload; 5] = [
  CommandPayload::NONE,
  CommandPayload::Increment,
  CommandPayload::Decrement,
  CommandPayload::Reset,
  CommandPayload::RollAndAdd,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct CommandPayload(pub u8);
#[allow(non_upper_case_globals)]
impl CommandPayload {
  pub const NONE: Self = Self(0);
  pub const Increment: Self = Self(1);
  pub const Decrement: Self = Self(2);
  pub const Reset: Self = Self(3);
  pub const RollAndAdd: Self = Self(4);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 4;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::NONE,
    Self::Increment,
    Self::Decrement,
    Self::Reset,
    Self::RollAndAdd,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::NONE => Some("NONE"),
      Self::Increment => Some("Increment"),
      Self::Decrement => Some("Decrement"),
      Self::Reset => Some("Reset"),
      Self::RollAndAdd => Some("RollAndAdd"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for CommandPayload {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for CommandPayload {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for CommandPayload {
    type Output = CommandPayload;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for CommandPayload {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for CommandPayload {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for CommandPayload {}
pub struct CommandPayloadUnionTableOffset {}

pub enum IncrementOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Increment<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Increment<'a> {
  type Inner = Increment<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Increment<'a> {
  pub const VT_AMOUNT: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Increment { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args IncrementArgs
  ) -> ::flatbuffers::WIPOffset<Increment<'bldr>> {
    let mut builder = IncrementBuilder::new(_fbb);
    builder.add_amount(args.amount);
    builder.finish()
  }


  #[inline]
  pub fn amount(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(Increment::VT_AMOUNT, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for Increment<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<i64>("amount", Self::VT_AMOUNT, false)?
     .finish();
    Ok(())
  }
}
pub struct IncrementArgs {
    pub amount: i64,
}
impl<'a> Default for IncrementArgs {
  #[inline]
  fn default() -> Self {
    IncrementArgs {
      amount: 0,
    }
  }
}

pub struct IncrementBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> IncrementBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_amount(&mut self, amount: i64) {
    self.fbb_.push_slot::<i64>(Increment::VT_AMOUNT, amount, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> IncrementBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    IncrementBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Increment<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Increment<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Increment");
      ds.field("amount", &self.amount());
      ds.finish()
  }
}
pub enum DecrementOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Decrement<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Decrement<'a> {
  type Inner = Decrement<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Decrement<'a> {
  pub const VT_AMOUNT: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Decrement { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args DecrementArgs
  ) -> ::flatbuffers::WIPOffset<Decrement<'bldr>> {
    let mut builder = DecrementBuilder::new(_fbb);
    builder.add_amount(args.amount);
    builder.finish()
  }


  #[inline]
  pub fn amount(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(Decrement::VT_AMOUNT, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for Decrement<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<i64>("amount", Self::VT_AMOUNT, false)?
     .finish();
    Ok(())
  }
}
pub struct DecrementArgs {
    pub amount: i64,
}
impl<'a> Default for DecrementArgs {
  #[inline]
  fn default() -> Self {
    DecrementArgs {
      amount: 0,
    }
  }
}

pub struct DecrementBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> DecrementBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_amount(&mut self, amount: i64) {
    self.fbb_.push_slot::<i64>(Decrement::VT_AMOUNT, amount, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> DecrementBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    DecrementBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Decrement<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Decrement<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Decrement");
      ds.field("amount", &self.amount());
      ds.finish()
  }
}
pub enum ResetOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Reset<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Reset<'a> {
  type Inner = Reset<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Reset<'a> {

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Reset { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    _args: &'args ResetArgs
  ) -> ::flatbuffers::WIPOffset<Reset<'bldr>> {
    let mut builder = ResetBuilder::new(_fbb);
    builder.finish()
  }

}

impl ::flatbuffers::Verifiable for Reset<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .finish();
    Ok(())
  }
}
pub struct ResetArgs {
}
impl<'a> Default for ResetArgs {
  #[inline]
  fn default() -> Self {
    ResetArgs {
    }
  }
}

pub struct ResetBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ResetBuilder<'a, 'b, A> {
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ResetBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ResetBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Reset<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Reset<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Reset");
      ds.finish()
  }
}
pub enum RollAndAddOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct RollAndAdd<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for RollAndAdd<'a> {
  type Inner = RollAndAdd<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> RollAndAdd<'a> {
  pub const VT_MIN: ::flatbuffers::VOffsetT = 4;
  pub const VT_MAX: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    RollAndAdd { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args RollAndAddArgs
  ) -> ::flatbuffers::WIPOffset<RollAndAdd<'bldr>> {
    let mut builder = RollAndAddBuilder::new(_fbb);
    builder.add_max(args.max);
    builder.add_min(args.min);
    builder.finish()
  }


  #[inline]
  pub fn min(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(RollAndAdd::VT_MIN, Some(0)).unwrap()}
  }
  #[inline]
  pub fn max(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(RollAndAdd::VT_MAX, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for RollAndAdd<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<i64>("min", Self::VT_MIN, false)?
     .visit_field::<i64>("max", Self::VT_MAX, false)?
     .finish();
    Ok(())
  }
}
pub struct RollAndAddArgs {
    pub min: i64,
    pub max: i64,
}
impl<'a> Default for RollAndAddArgs {
  #[inline]
  fn default() -> Self {
    RollAndAddArgs {
      min: 0,
      max: 0,
    }
  }
}

pub struct RollAndAddBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> RollAndAddBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_min(&mut self, min: i64) {
    self.fbb_.push_slot::<i64>(RollAndAdd::VT_MIN, min, 0);
  }
  #[inline]
  pub fn add_max(&mut self, max: i64) {
    self.fbb_.push_slot::<i64>(RollAndAdd::VT_MAX, max, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> RollAndAddBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    RollAndAddBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<RollAndAdd<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for RollAndAdd<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("RollAndAdd");
      ds.field("min", &self.min());
      ds.field("max", &self.max());
      ds.finish()
  }
}
pub enum CommandMessageOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct CommandMessage<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for CommandMessage<'a> {
  type Inner = CommandMessage<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> CommandMessage<'a> {
  pub const VT_PAYLOAD_TYPE: ::flatbuffers::VOffsetT = 4;
  pub const VT_PAYLOAD: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    CommandMessage { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args CommandMessageArgs
  ) -> ::flatbuffers::WIPOffset<CommandMessage<'bldr>> {
    let mut builder = CommandMessageBuilder::new(_fbb);
    if let Some(x) = args.payload { builder.add_payload(x); }
    builder.add_payload_type(args.payload_type);
    builder.finish()
  }


  #[inline]
  pub fn payload_type(&self) -> CommandPayload {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<CommandPayload>(CommandMessage::VT_PAYLOAD_TYPE, Some(CommandPayload::NONE)).unwrap()}
  }
  #[inline]
  pub fn payload(&self) -> Option<::flatbuffers::Table<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Table<'a>>>(CommandMessage::VT_PAYLOAD, None)}
  }
  #[inline]
  #[allow(non_snake_case)]
  pub fn payload_as_increment(&self) -> Option<Increment<'a>> {
    if self.payload_type() == CommandPayload::Increment {
      self.payload().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { Increment::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn payload_as_decrement(&self) -> Option<Decrement<'a>> {
    if self.payload_type() == CommandPayload::Decrement {
      self.payload().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { Decrement::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn payload_as_reset(&self) -> Option<Reset<'a>> {
    if self.payload_type() == CommandPayload::Reset {
      self.payload().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { Reset::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn payload_as_roll_and_add(&self) -> Option<RollAndAdd<'a>> {
    if self.payload_type() == CommandPayload::RollAndAdd {
      self.payload().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { RollAndAdd::init_from_table(t) }
     })
    } else {
      None
    }
  }

}

impl ::flatbuffers::Verifiable for CommandMessage<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_union::<CommandPayload, _>("payload_type", Self::VT_PAYLOAD_TYPE, "payload", Self::VT_PAYLOAD, false, |key, v, pos| {
        match key {
          CommandPayload::Increment => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<Increment>>("CommandPayload::Increment", pos),
          CommandPayload::Decrement => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<Decrement>>("CommandPayload::Decrement", pos),
          CommandPayload::Reset => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<Reset>>("CommandPayload::Reset", pos),
          CommandPayload::RollAndAdd => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<RollAndAdd>>("CommandPayload::RollAndAdd", pos),
          _ => Ok(()),
        }
     })?
     .finish();
    Ok(())
  }
}
pub struct CommandMessageArgs {
    pub payload_type: CommandPayload,
    pub payload: Option<::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>>,
}
impl<'a> Default for CommandMessageArgs {
  #[inline]
  fn default() -> Self {
    CommandMessageArgs {
      payload_type: CommandPayload::NONE,
      payload: None,
    }
  }
}

pub struct CommandMessageBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> CommandMessageBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_payload_type(&mut self, payload_type: CommandPayload) {
    self.fbb_.push_slot::<CommandPayload>(CommandMessage::VT_PAYLOAD_TYPE, payload_type, CommandPayload::NONE);
  }
  #[inline]
  pub fn add_payload(&mut self, payload: ::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(CommandMessage::VT_PAYLOAD, payload);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> CommandMessageBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    CommandMessageBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<CommandMessage<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for CommandMessage<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("CommandMessage");
      ds.field("payload_type", &self.payload_type());
      match self.payload_type() {
        CommandPayload::Increment => {
          if let Some(x) = self.payload_as_increment() {
            ds.field("payload", &x)
          } else {
            ds.field("payload", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        CommandPayload::Decrement => {
          if let Some(x) = self.payload_as_decrement() {
            ds.field("payload", &x)
          } else {
            ds.field("payload", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        CommandPayload::Reset => {
          if let Some(x) = self.payload_as_reset() {
            ds.field("payload", &x)
          } else {
            ds.field("payload", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        CommandPayload::RollAndAdd => {
          if let Some(x) = self.payload_as_roll_and_add() {
            ds.field("payload", &x)
          } else {
            ds.field("payload", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        _ => {
          let x: Option<()> = None;
          ds.field("payload", &x)
        },
      };
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `CommandMessage`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_command_message_unchecked`.
pub fn root_as_command_message(buf: &[u8]) -> Result<CommandMessage<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<CommandMessage>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `CommandMessage` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_command_message_unchecked`.
pub fn size_prefixed_root_as_command_message(buf: &[u8]) -> Result<CommandMessage<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<CommandMessage>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `CommandMessage` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_command_message_unchecked`.
pub fn root_as_command_message_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<CommandMessage<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<CommandMessage<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `CommandMessage` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_command_message_unchecked`.
pub fn size_prefixed_root_as_command_message_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<CommandMessage<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<CommandMessage<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a CommandMessage and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `CommandMessage`.
pub unsafe fn root_as_command_message_unchecked(buf: &[u8]) -> CommandMessage<'_> {
  unsafe { ::flatbuffers::root_unchecked::<CommandMessage>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed CommandMessage and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `CommandMessage`.
pub unsafe fn size_prefixed_root_as_command_message_unchecked(buf: &[u8]) -> CommandMessage<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<CommandMessage>(buf) }
}
#[inline]
pub fn finish_command_message_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<CommandMessage<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_command_message_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<CommandMessage<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod Contracts
}  // pub mod Grafting

